name: Large Dataset Datacap Application
description: Clients should use this application form to request a DataCap allocation via a LDN for a dataset
title: "[DataCap Application] <Organization> - <Project Name>"
labels: 'application, Phase: Diligence'
body:
- type: markdown
  attributes:
    value: |
      # Large Dataset Notary Application
      To apply for DataCap to onboard your dataset to Filecoin, please fill out the following form
- type: markdown
  attributes:
    value: |
      # Company
- type: input
  attributes:
    label: Introduce your company
  validations:
    required: true
- type: input
  attributes:
    label: Website
  validations:
    required: true
- type: input
  attributes:
    label: How many employees does your company have?
  validations:
    required: true
- type: input
  attributes:
    label: On-chain address for first allocation
  validations:
    required: true
- type: input
  attributes:
    label: What is your industry?
  validations:
    required: true
- type: input
  attributes:
    label: What type of data do you want to store?
  validations:
    required: true
- type: textarea
  attributes:
    label: Why does your company store data on the Filecoin network?
    render: text
  validations:
    required: true
- type: textarea
  attributes:
    label: How do you verify your identity?
    render: text
  validations:
    required: true
- type: input
  attributes:
    label: Can you send us emails using your business domain email?
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      # Data
- type: input
  attributes:
    label: Total amount of DataCap being requested
  validations:
    required: true
- type: input
  attributes:
    label: Expected size of single dataset (one copy)
  validations:
    required: true
- type: input
  attributes:
    label: Weekly allocation of DataCap requested
  validations:
    required: true
- type: input
  attributes:
    label: How much data does your company have?
  validations:
    required: true
- type: input
  attributes:
    label: Can you provide data examples?
  validations:
    required: true
- type: input
  attributes:
    label: Has this dataset been stored on Filecoin before?
  validations:
    required: true
- type: input
  attributes:
    label: How long do you plan to store it ?
  validations:
    required: true
- type: input
  attributes:
    label: What is the expected retrieval frequency for this data?
  validations:
    required: true
- type: input
  attributes:
    label: Where is your data currently stored?
  validations:
    required: true
- type: input
  attributes:
    label: Where do you want your data to be stored?
  validations:
    required: true
- type: input
  attributes:
    label: How much backup do you want of your data?
  validations:
    required: true
- type: input
  attributes:
    label: Confirm that this is a public dataset that can be retrieved by anyone on the Network
  validations:
    required: true
- type: markdown
  attributes:
    value: |
      # Technology
- type: textarea
  attributes:
    label: How many members about your technical team?
    render: text
  validations:
    required: true
- type: textarea
  attributes:
    label: Please list the storage providers you cooperate with
    render: text
  validations:
    required: true
- type: textarea
  attributes:
    label: How will the data be prepared? Please include tooling used and technical details
    render: text
  validations:
    required: true
- type: textarea
  attributes:
    label: How will you be distributing your data to storage providers
    render: text
  validations:
    required: true
- type: textarea
  attributes:
    label: Do you need our help?Please list it in detail
    render: text
  validations:
    required: true
- type: textarea
  attributes:
    label: Can you confirm that you will follow the Fil+ guideline
    render: text
  validations:
    required: true
